# .github/workflows/test.yml

name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          pipenv install --deploy --dev

      - run: pipenv run isort --recursive --diff .
      - run: pipenv run flake8

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t holiday_reminder

      - name: Test image
        run: |
          docker run --rm -d --name test_container -p 8000:8000 holiday_reminder
          docker run --link test_container:test_container waisbrot/wait
          curl --fail http://localhost:8000